---
title: "Untitled"
author: "TC"
date: "12/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
library(rvest)
library(xml2)
library(htmltab)
```


```{r}
url = "https://ja.wikipedia.org/wiki/M-1%E3%82%B0%E3%83%A9%E3%83%B3%E3%83%97%E3%83%AA"
```



xpath

//*[@id="mw-content-text"]/div/table[17]

```{r}
# tbl = 

test = 
  url %>% 
  xml2::read_html() %>% 
  xml2::xml_find_all(xpath='//*[@id="mw-content-text"]/div/table[descendant::caption]/tbody')
  # htmltab::
  # htmltab(2)
```


```{r}
url %>% 
  htmltab(which = '(//*[@id="mw-content-text"]/div/table[descendant::caption])[3]', rm_nodata_cols=F)
```


```{r}
dfall = lapply(1:15, function(i){
  myxpath = sprintf('(//*[@id="mw-content-text"]/div/table[descendant::caption])[%d]', i)
  
  df = url %>% 
    htmltab( which = myxpath)
  return(df)
})
```

```{r}
library(dplyr)
```

```{r}
df.cln = lapply(1:length(dfall), function(i){
  
  df = dfall[[i]][,c(1,2)]
  njudge = 7
  
  if (i == 12) njudge = 5
  if (i == 11) njudge = 9
  if (i ==1){
    df = dfall[[i]][,c(1,3)]
  }
  
  names(df) = c("combi","FirstR_score")

  df.tmp = df %>%  select(1,2) %>% 
    mutate(FirstR_score=as.numeric(FirstR_score)) %>% 
    mutate (M1=i,
            avgFRS=FirstR_score/njudge)
  
   
    
  return(df.tmp)
})

df.all = do.call(rbind,df.cln)

```

```{r}
# df.all.anno =
df.all.anno = 
df.all %>% 
  group_by(M1) %>% 
  mutate(FirstR_score = as.numeric(FirstR_score)) %>% 
  mutate(rank=  rank(- FirstR_score, ties.method="first")) %>% 
  mutate(rank=factor(rank, level=1:10)) 
```

```{r}
library(ggrepel)
```

```{r}
df.all.anno.sort = 
df.all.anno %>% 
  ungroup() %>% 
  arrange(desc(avgFRS)) %>% 
  slice(1:3) %>% 
  mutate(myrank=row_number()) %>% 
  mutate(mylabel= sprintf("%d %s %.2f",myrank,combi, avgFRS))
```


```{r}

gg = 
df.all.anno %>% 
  ggplot(aes(x=M1,y=avgFRS, color = rank,group =rank))+
  geom_point()+geom_line()+
  geom_text_repel(data = df.all.anno.sort, aes(label=mylabel),color="black")+
  # geom_text_repel(data = df.all.anno %>% filter(combi=="和牛"), aes(label=combi)@)+
  scale_x_continuous(breaks=1:15)+ xlab("")+
  
  scale_y_continuous(breaks=seq(65,100,5))+
  ylab("Avg first round score")

gg
```

```{r}
df.all.anno %>% 
  group_by(M1) %>% 
  summarise(medavg= median(avgFRS)) %>% 
  ggplot(aes(M1,y=medavg))+
  geom_point()
```

