---
title: "Untitled"
author: "TC"
date: "10/24/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
library(dplyr)
library(xml2)
library(tidyr)
library(lubridate)
# html_table()
```

## scrape it


```{r}

extract_summary = function(suburl) {
  Sys.sleep(1)
  
  summary = 
  suburl %>%
    read_html() %>%
    xml_find_all('//*[@class="summernote"]') %>%
    xml_text()
  return(summary)
}

extractit = function(url) {
  # url = "https://www.tv-asahi.co.jp/londonhearts/backnumber/backnumber.html?"
  
  tmpurl = url %>%
    read_html()
  
  records =
    tmpurl %>%
    xml_find_all(xpath = '//*[@class="backnumber-list-box"]/ul/li')
  
  date =
    records %>%
    xml_find_all(xpath = "//*[@class='date']") %>%
    xml_text()
  
  title =
    records %>%
    xml_find_all(xpath = ".//*[@class='txt']") %>%
    xml_text()
  
  link =
    tmpurl %>%
    xml_find_all(xpath = '//*[@class="backnumber-list-box"]/ul/li/a') %>%
    xml_attr("href")
  
  link=paste0("https://www.tv-asahi.co.jp", link)
  
  summary = pbapply::pbsapply(link, extract_summary)
  
  return(tibble(date, title, link, summary))
  
}

```

```{r eval=FALSE}

url = "https://www.tv-asahi.co.jp/londonhearts/backnumber/backnumber.html?"

data.lh = extractit(url)
```

```{r}
save(data.lh, file = here::here("/data/data.lh.rda"))
```

## clean

```{r}
load(here::here("/data/data.lh.rda"))
```

```{r}
data.lh.cln =
data.lh %>%
  mutate(date=gsub("(.*日).*","\\1",date),
         publishdate = as_date(date))
```


## map to existing files

```{r}
# gt_posts = data.table::fread("~/GIT/lhdata/data/known_godtongue.txt", header=FALSE)

postlist = list.files("~/GIT/owaraisite/content/post/", pattern=".*-.*.md", full.names=TRUE)

```


```{r}
get_postmeta= function(fpost){
  lines = xfun::file_string(fpost)
  content = gsub("^---.*?---\n", "", lines)
  header = gsub("^---(.*?)\n---\n.*", "\\1", lines)
  
  rslt = try(yaml::yaml.load(header))
  
  rslt.df = data.frame(
    title= rslt$title,
    slug = rslt$slug,
    publishdate = rslt$publishdate,
    bangumi = rslt$bangumi,
    
    stringsAsFactors=FALSE
  )
  
  return(rslt.df)
}

get_postmeta_v = function(postlist){
  rslt.df.l = lapply(postlist, get_postmeta)
  
  rslt.df.l.df = do.call(rbind, rslt.df.l)
  
  rslt.df.l.df$fpost = postlist
  return(rslt.df.l.df)
}
```


```{r}
mydata = get_postmeta_v(postlist)
```


```{r}

get_subbed = function(mydata, kw) {
  subbed_data = mydata %>%
    mutate(publishdate = as_date(publishdate)) %>%
    mutate(publishdate_nb1 = publishdate - 1,
           publishdate_nb2 = publishdate + 1) %>%
    mutate(
      av = gsub(".*-(.*)", "\\1", slug),
      link = paste0("<a href='",
                    "/post/",
                    slug,
                    "'>LINK</a>")
    ) %>%
    pivot_longer(
      cols = starts_with("publishdate"),
      names_to = "dummy",
      values_to = "publishdate"
    ) %>%
    select(-dummy) %>%
    filter(bangumi == kw)
}

lh_subbed = get_subbed(mydata, "伦敦之心")
```

```{r}
lh_list.cln = data.lh.cln %>%
  left_join(lh_subbed, by=c("publishdate" = "publishdate"))
```


```{r}
save(lh_list.cln, file=here::here("/data/lh_list.cln.rda"))
```






