---
title: "Untitled"
author: "TC"
date: "10/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
library(dplyr)
library(xml2)
library(tidyr)
library(lubridate)
# html_table()
```

## R Markdown

```{r}
url = "https://www.tv-asahi.co.jp/ametalk/backnumber/"
```

```{r}
urls= paste0(url, "backnumber",2006:2018,".html")

urlsall=c(urls,
          "https://www.tv-asahi.co.jp/ametalk/backnumber/backnumber.html")
```


```{r}

extract_guest = function(suburl) {
  
  Sys.sleep(1)

  guest =
    suburl %>%
    read_html() %>%
    xml2::xml_find_all(xpath = './/div[@class="txt-box-detail summernote"]/p') %>%
    xml2::xml_contents() %>%
    as.character()
  # xml2::xml_children() %>%
  
  guest.cln =
    stringr::str_trim(guest[grepl("[\u3040-\u309f]|[\u30a0-\u30ff]", guest)]) %>%
    paste0(collapse = "＆")
  return(guest.cln)
}

extractit = function(url) {
  
  year = basename(url) %>% gsub("backnumber(.*).html","\\1",.)
  
  if (stringr::str_length(year) <2) year = lubridate::year(Sys.Date())
  
  tmphtml = url %>% read_html()
  
  title = tmphtml %>%
    xml_find_all(xpath = "/html/body/ul[2]/li/a/p") %>%
    as.character() %>%
    gsub("<p .*?>(.*)</p>", "\\1", .) %>%
    gsub("(.*)<br>(.*)", "\\2", .)

  date = tmphtml %>%
    xml_find_all(xpath = "/html/body/ul[2]/li/a/p") %>%
    as.character() %>%
    gsub("<p .*?>(.*)</p>", "\\1", .) %>%
    gsub("(.*)<br>(.*)", "\\1", .) %>%
    paste0(year,"年",.) 
  
  link = tmphtml %>%
    xml_find_all(xpath = "/html/body/ul[2]/li/a") %>%
    xml_attr("href") %>%
    paste0("https://www.tv-asahi.co.jp", .)
  
  summary = pbapply::pbsapply(link, extract_guest)
  
  df = tibble(date, title, link, summary)

  return(df)
}


```

```{r eval=FALSE}
extractit(urlsall[14])
```



```{r eval=FALSE}
data.ame = lapply(urlsall, extractit)

data.ame.all = do.call(rbind, data.ame)

save(data.ame.all, file = here::here("/data/data.ame.all.rda"))
```

## clean it up


```{r}
load(here::here("/data/data.ame.all.rda"))
```




## map to existing files

```{r}
# gt_posts = data.table::fread("~/GIT/lhdata/data/known_godtongue.txt", header=FALSE)

postlist = list.files("~/GIT/owaraisite/content/post/", pattern=".*-.*.md", full.names=TRUE)


mydata = get_postmeta_v(postlist)


data.ame.cln = 
data.ame.all %>%
  mutate(date2= lubridate::as_date(gsub("(.*?日).*","\\1", date)))

ametalk_subbed = mydata %>%
  mutate(publishdate = as_date(publishdate)) %>%
  filter(bangumi == "ametalk") 

ame_list.cln = data.ame.cln %>%
  mutate(publishdate = date2) %>%
  left_join(ametalk_subbed, by=c("publishdate" = "publishdate"))

save(ame_list.cln, file=here::here("/data/ame_list.cln.rda"))
```




