---
title: "Untitled"
author: "TC"
date: "10/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(htmltab)
library(dplyr)
library(lubridate)
library(tidyr)
```

## Scrape it



```{r}
### https://stackoverflow.com/questions/47585699/rvest-html-table-error-error-in-outj-k-subscript-out-of-bounds

## htmltab handles tables better


tmp_get_wikitable = function(i, url) {
  tbl =
    url %>%
  htmltab(i)
  
  tbl$year = gsub("(.*) >>.*", "\\1", colnames(tbl)[1])
  colnames(tbl) = gsub(".* >> (.*)","\\1", colnames(tbl))
  tbl = as_tibble(tbl)
  return(tbl)
}

```


```{r}
url = "https://ja.wikipedia.org/wiki/%E3%82%B4%E3%83%83%E3%83%89%E3%82%BF%E3%83%B3#%E6%94%BE%E9%80%81%E3%83%AA%E3%82%B9%E3%83%88"

```


```{r}
tbl= pbapply::pblapply(3:17, tmp_get_wikitable, url=url)
```

```{r}
tbl.tmp = lapply(tbl, function(df){
  colnames(df) = c("a", "b", "c", "d", "e")
  return(df)
})

godtong_list = do.call(rbind, tbl.tmp)

# save(godtong_list, file = "~/GIT/lhdata/data/godtongue_list.rda")
```


## map to existing files

```{r}
# gt_posts = data.table::fread("~/GIT/lhdata/data/known_godtongue.txt", header=FALSE)

postlist = list.files("~/GIT/owaraisite/content/post/", pattern=".*-.*.md", full.names=TRUE)

```


```{r}
get_postmeta= function(fpost){
  lines = xfun::file_string(fpost)
  content = gsub("^---.*?---\n", "", lines)
  header = gsub("^---(.*?)\n---\n.*", "\\1", lines)
  
  rslt = try(yaml::yaml.load(header))
  
  rslt.df = data.frame(
    title= rslt$title,
    slug = rslt$slug,
    publishdate = rslt$publishdate,
    bangumi = rslt$bangumi,
    
    stringsAsFactors=FALSE
  )
  
  return(rslt.df)
}

get_postmeta_v = function(postlist){
  rslt.df.l = lapply(postlist, get_postmeta)
  
  rslt.df.l.df = do.call(rbind, rslt.df.l)
  
  rslt.df.l.df$fpost = postlist
  return(rslt.df.l.df)
}
```


```{r}
mydata = get_postmeta_v(postlist)
```


```{r}
godtong_subbed = mydata %>%
  mutate(publishdate = as_date(publishdate)) %>%
mutate(publishdate_nb1 = publishdate - 1,
       publishdate_nb2 = publishdate + 1) %>%
  mutate(
    av = gsub(".*-(.*)", "\\1", slug),
    link = paste0(
      "<a href='",
      "/post/",
      slug,
      "'>LINK</a>"
    )
  ) %>%
  pivot_longer(cols =starts_with("publishdate"),
               names_to="dummy",
               values_to="publishdate") %>%
  select(-dummy) %>%
  filter(bangumi == "神舌") 
```

```{r}
godtong_list.cln = godtong_list %>%
  mutate(publishdate = as_date(paste0(e,b))) %>%
  left_join(godtong_subbed, by=c("publishdate" = "publishdate"))
```


```{r}
save(godtong_list.cln, file=here::here("/data/godtongue_list_cln.rda"))
```




