---
title: "Untitled"
author: "TC"
date: "October 24, 2017"
output: html_document
---

```{r setup, include=FALSE,message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(lubridate)
pkg_path="~/GIT/lhdata"
post_path="~/GIT/owaraisite/content/post/"


source(encoding="UTF-8",file=paste0(pkg_path,"/R/api_getuploads.R"))
source(encoding="UTF-8",file=paste0(pkg_path,"/R/api_getuploads_fp.R"))
source(encoding="UTF-8",file=paste0(pkg_path,"/R/getbangumi.R"))
source(encoding="UTF-8",file=paste0(pkg_path,"/R/getyearsdf.R"))
source(encoding="UTF-8",file=paste0(pkg_path,"/R/api_aid2cid.R"))
source(encoding="UTF-8",file=paste0(pkg_path,"/R/api_getbilitags.R"))
source(encoding="UTF-8",file=paste0(pkg_path,"/R/api_upload_imgur.R"))
source(encoding="UTF-8",file=paste0(pkg_path,"/R/generate_posts2.R"))
source(encoding="UTF-8",file=paste0(pkg_path,"/R/annotate_vlist.R"))
load(paste0(pkg_path,"/data/mid.rda"))
load(paste0(pkg_path,"/data/manual_filter.rda"))
```

```{r eval=FALSE}



mid.df <- data.frame(mids = c(5382023,
                              207626,
                              2301165,
                              26666749,
                              97990,
                              8665350),
                     author = c("九條",
                                "莱姆籽",
                                "天翼羽魂",
                                "来一发就走字幕组",
                                "小山君",
                                "叔叔"),
                     zmz = c("伦敦之心字幕组",
                             "伦敦之心字幕组",
                             "伦敦之心字幕组",
                             "来一发就走字幕组",
                             "大喜利王字幕组",
                             "4431字幕组"
                             ),
                     kw = c("",
                            "伦敦之心字幕组",
                            "人力",
                            "",
                            "",
                            "字幕"),
                     stringsAsFactors = FALSE)
save(mid.df,file=paste0(pkg_path,"/data/mid.rda"))

```




## downloadthings

```{r}
message("###########################################################")
message(Sys.time())
message("...start scraping\n")
#source(encoding="UTF-8",file=paste0(pkg_path,"/R/api_getuploads.R")


vlist.all <- data.frame()

for ( i in c(1,4,5,6)){
  vlist <- api_getuploads_fp(mid.df$mids[i],kw=mid.df$kw[i])
  vlist$zmz=mid.df$zmz[i]
  vlist.all <- rbind(vlist.all,vlist)
}



## get new vlist
p= list.files(post_path)
oldaid <- ((gsub('^.*-(.*).md$','\\1',p)))


vlist.new <- vlist.all %>% 
  filter(!aid %in% oldaid, !aid %in% manual_filter$aid)



message("###########################################################")

message(paste0("...scraping finished, ",nrow(vlist.new)," new posts"))
if (nrow(vlist.new)==0) {
  message("...no new post detected, quitting script")
  q('no')
}

```


```{r eval=FALSE}
filter_update <- unique(rbind(manual_filter,data.frame(aid=oldaid)))

manual_filter <- data.frame(aid=oldaid)
save(manual_filter,file=paste0(pkg_path,"/data/manual_filter.rda"))
```

```{r test, eval=FALSE}
vlist.new <-api_getuploads(5738638)

vlist.new$zmz="生姜小分队字幕组"

#vlist.new.anno$zmz="伦敦之心字幕组"
```


## add info

```{r}
## vlist add more columns using api
## require vlist.new
message("###########################################################")
message("...starting downloading pics\n")
#source("../R/annotate_vlist.R")
vlist.new.anno <-annotate_vlist(vlist.new)

```

## output

```{r}
message("###########################################################")
message("...starting generating pics")
message("###########################################################")

generate_post2(vlist.new.anno,post_path)
```



