---
title: "Untitled"
author: "TC"
date: "6/24/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

post_path="~/GIT/owaraisite/content/post/"

library(dplyr)

```

## data

```{r}
allfiles = list.files(post_path, full.names = TRUE)
df = data.frame(path = allfiles, stringsAsFactors = FALSE) %>%
  filter(!grepl("index", path)) %>%
  mutate(name = basename(path),
         aid = gsub(".*-(.*).md", "\\1", name))
codes = vector(length = nrow(df))

```


## Goal

check if videos are down



```{r}
api_is_aid_alive = function(aid = 56447372){
  # url2 =paste0("http://api.bilibili.com/x/reply?type=1&oid=",aid)
  url3 = paste0("https://api.bilibili.com/x/web-interface/archive/stat?aid=",aid)
  rslt = jsonlite::fromJSON(url3)$code
  return(rslt)
}
```





```{r}

get_title = function(path) {
  d =
    xfun::file_string(path) %>%
    
    stringr::str_match("title:(.*)\n") %>%
    stringr::str_trim()
  
  
  try((rslt = d[2]))
  
  return(rslt)
}
```


```{r}
get_basicinfo = function(path) {
  tmpl =
    xfun::file_string(path) %>%
    # gsub(".*(---.*?\n---\n).*","\\1", .) 
    gsub("^---\n(.*?)\n---\n.*","\\1", .)
  
  tmpyaml = try((yaml::read_yaml(text=tmpl)))
  
  return(tmpyaml)
  

}
```


```{r debug eval = FALSE}
# get_basicinfo("/home/tc/GIT/owaraisite/content/post//2019-03-30-NA-47632906.md")

xfun::file_string("/home/tc/GIT/owaraisite/content/post//2018-07-28-121108-27945361.md") %>%
  gsub("^---\n(.*?)\n---\n.*","\\1", .)  %>%
  yaml::read_yaml(text = .)
```


```{r}
all.yamls = lapply(df$path, get_basicinfo)
df$title = sapply(all.yamls, function(l) l$title)
df$bangumi = sapply(all.yamls, function(l) l$bangumis)
df$zmz = sapply(all.yamls, function(l) l$author[[1]])
df$date = sapply(all.yamls, function(l) l$date)
```

```{r}

```







```{r eval=FALSE}
for (i in 1:length(codes)){
  codes[i] = api_is_aid_alive(df$aid[i])
  Sys.sleep(0.1)
  message(i,"finished")
}
```

```{r eval= FALSE}
# slow, ~25 min
tmp = pbapply::pbsapply(df$aid, api_is_aid_alive)

save(tmp, file="../data/tmp.rda")
```

```{r}
load("../data/tmp.rda")
df$is.alive = tmp
```


```{r eval= FALSE}
# df$title = sapply(df$path,get_title)

save(df, file="../data/post_is_alive.rda")
```




