---
title: "wordcloud_data"
author: "TC"
date: "November 6, 2017"
output: html_document
---

```{r setup, include=FALSE,message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pkg_path="~/GIT/lhdata"
bangumipath="~/GIT/owaraisite/static/js/bangumi_data.js"
tagpath="~/GIT/owaraisite/static/js/tag_data.js"
url_bangumi= "http://owaraiclub.com/bangumis/"
url_tag="http://owaraiclub.com/tags/"

library(XML)
library(RCurl)
library(rlist)
library(stringr)
library(dplyr)


```



```{r}


update_wordcloud_data <- function(url, filepath) {
  theurl <- RCurl::getURL(url)
  mylist <- XML::readHTMLList(theurl)
  taglist <- mylist[[2]]
  tmptag <-
    stringr::str_split(taglist, pattern = "\r\n    \r\n    |\n    \n    ")
  tmptag.df <- as.data.frame(do.call(rbind, tmptag))
  tmptag.df.final <-
    tmptag.df %>%
    mutate(word = V1, freq = as.numeric(stringr::str_extract(V2, "\\d{1,}"))) %>%
    select(word, freq)
  
  jsline <-
    paste0 ("var db = ", jsonlite::toJSON(tmptag.df.final), ";")
  
  fileConn <- file(filepath)
  writeLines(jsline, fileConn)
  close(fileConn)
  
  message(filepath," updated")
}

```

```{r}
message("###########################################################")
message(Sys.time(),"...updating wordcloud\n")

update_wordcloud_data(url_tag,tagpath)

update_wordcloud_data(url_bangumi,bangumipath)

message("###########################################################")
message(Sys.time(),"...wordcloud updated!\n")


```



